### ISSUE TITLE
be clear about "virtual nature" of these datasets

### ISSUE THREAD

**Issue by mpo-vliz** [fair-ease/dataset-demand-register#4]
I like how we link in with DataSet and DataCalog in the current design, plus how we complement into direction of describing the schema of it 

however... we might now confuse people into believing these new URI are pointing to "actual datasets"

the fact that these are real definitions, and contracts and expectations, but not actually containing the goods (ie the data should be made clear)

maybe something like https://schema.org/Demand could help?

**Comment by laurianvm** [comment]
Looking into [schema:Demand](https://schema.org/Demand) - it might be interesting to turn it around and use [schema:Offer](https://schema.org/Offer), has interesting properties like [additionalProperty](https://schema.org/additionalProperty) (~ "...representing an additional characteristic of the entity")
